Add TemporalPlainTime
Samsung/escargot pull request #1112
Opened 2022-06-24 06:33 UTC by gergocs

Signed-off-by: Gergo Csizi gergocs@inf.u-szeged.hu

2022-06-24 07:26 UTC, zherczeg requested changes

2022-06-24 07:26 UTC, zherczeg commented on src/builtins/BuiltinTemporal.cpp
> +    TemporalPlainTime* two = TemporalPlainTime::toTemporalTime(state, argv[1], Value()).asObject()->asTemporalPlainTimeObject();
one/two? Is there a better name?

2022-06-24 07:26 UTC, zherczeg commented on src/builtins/BuiltinTemporal.cpp
> +    if (!(argc > 0 && argv[0].isInteger(state)) || !(argc > 1 && argv[1].isInteger(state)) || !(argc > 2 && argv[2].isInteger(state)) || !(argc > 3 && argv[3].isInteger(state)) || !(argc > 4 && argv[
I don't really like this huge check, maybe a `for` loop could be used here:
```
int values[6];
memset(values, 0, sizeof(values));

for (int i = 0; i < argc && i < 6; i++) {
  if (!(argv[0].isInteger(state))) {
    ErrorObject::throwBuiltinError(state, ErrorObject::TypeError, "Invalid type");
  }
  values[i] = argv[i].asInt32();
}
```

Then the values could be passed to createTemporalTime.

2022-06-24 07:26 UTC, zherczeg commented on src/runtime/Temporal.h
> +            return new Object(state, Object::PrototypeIsNull);
Do we need to create an object here? I usually prefer a constant such as null/undefined here.

2022-06-24 07:26 UTC, zherczeg commented on src/runtime/TemporalObject.cpp
> +    if (options.isUndefined()) {
Can it be undefined? It is always converted to object. It could be if you use the undefined value idea above though.

2022-06-24 09:42 UTC, gergocs commented
Patch is ready for review

2022-06-24 09:49 UTC, zherczeg approved these changes
LGTM with minor fix

2022-06-24 09:49 UTC, zherczeg commented on src/builtins/BuiltinTemporal.cpp
> +
One newline.

2022-06-27 04:27 UTC, ksh8281 approved these changes

2022-06-27 04:27 UTC, merged