Implement String , TypeArray and Array.prototype.at
Samsung/escargot pull request #825
Opened 2021-01-28 09:26 UTC by kisbg

https://tc39.es/proposal-relative-indexing-method/#sec-array-prototype-additions

Signed-off-by: bence gabor kis <kisbg@inf.u-szeged.hu>

2021-02-01 02:36 UTC, ksh8281 commented
Could you rebase and re-push your pr?
there was an error on github actions tests. error is fixed now.

2021-02-01 02:41 UTC, ksh8281 commented on src/runtime/GlobalObjectBuiltinString.cpp
> +    char16_t k = str->charAt(relativeStart);
You can use String::fromCharCode

2021-02-01 02:42 UTC, ksh8281 commented on src/runtime/GlobalObjectBuiltinTypedArray.cpp
> +    return obj->get(state, ObjectPropertyName(state, Value(relativeStart).toString(state))).value(state, thisValue);
I belive we can remove toString operation.
just passing number into ObjectPropertyName(state, Value(relativeStart))

2021-02-01 07:14 UTC, kisbg commented
@ksh8281  Thank you for the review!

2021-02-01 11:18 UTC, clover2123 requested changes

2021-02-01 11:18 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinArray.cpp
> +    Object* obj = thisValue.asObject();
How about replacing this part with `RESOLVE_THIS_BINDING_TO_OBJECT`?

2021-02-01 11:18 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinArray.cpp
> +    return obj->get(state, ObjectPropertyName(state, Value(relativeStart).toString(state))).value(state, thisValue);
I think that we can simply call `getIndexedProperty` here because property name is an integer value.

2021-02-01 11:18 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinTypedArray.cpp
> +    Object* obj = thisValue.asObject();
It seems that this part can be removed because `validateTypedArray` checks the type of thisValue in itself.

2021-02-01 11:18 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinTypedArray.cpp
> +    return obj->get(state, ObjectPropertyName(state, Value(relativeStart))).value(state, thisValue);
Simply change `get` as to `getIndexedProperty` too.

2021-02-01 11:18 UTC, clover2123 commented on src/runtime/StaticStrings.h
>      F(abs)                        \
Keep the order please. Thank you :)

2021-02-02 06:03 UTC, ksh8281 approved these changes
Good!

2021-02-02 06:21 UTC, clover2123 approved these changes
LGTM

2021-02-02 06:21 UTC, merged