Implement Legacy RegExp features
Samsung/escargot pull request #832
Opened 2021-02-03 08:52 UTC by kisbg

Signed-off-by: bence gabor kis <kisbg@inf.u-szeged.hu>

2021-02-05 01:43 UTC, clover2123 commented
I cannot find `Legacy RegExp` features in the current [draft ECMA-262](https://tc39.es/ecma262/).
It seems that this spec is in the proposal stage and not yet written on the standard.
How about leaving this pr on pending until it is updated?

2021-02-08 07:31 UTC, kisbg commented
@clover2123  Sorry for the late reply! This pull request based on this proposal documentation `https://github.com/tc39/proposal-regexp-legacy-features`.

Of course i can close this pull request and wait for a more official standard documentation.

2021-02-08 08:15 UTC, clover2123 commented
@kisbg I've updated test262 to the latest version (#834)
After #834 landed, would you please check and re-run relevant test cases in the new test262?

2021-02-08 08:16 UTC, kisbg commented
@clover2123  Of course!

2021-02-09 11:32 UTC, kisbg commented
Updated the pull request and added the related test-cases in test262

2021-02-10 05:34 UTC, clover2123 requested changes

2021-02-10 05:34 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinRegExp.cpp
>      state.resolveCallee()->codeBlock()->context()->regexpStatus().input = argv[0].toString(state);
Why don't you call `setLegacyRegExpStaticProperty` here?

2021-02-10 05:49 UTC, clover2123 requested changes

2021-02-10 05:49 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinRegExp.cpp
> +        new NativeFunctionObject(state, NativeFunctionInfo(strings->set, builtinRegExpLastMatchSetter, 1, NativeFunctionInfo::Strict));
This newly allocated `NativeFunctionObject` seems useless.
And there are other similar cases like this. Please check and remove it.

2021-02-10 05:49 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinRegExp.cpp
> +{
According to the standard, `RegExp.lastMatch` does not have setter (getter only).
Remove this setter function and other setter functions too.

2021-02-10 05:54 UTC, clover2123 commented
`GetLegacyRegExpStaticProperty` and `SetLegacyRegExpStaticProperty` are abstract operations that means we don't have to implement these functions exactly as spec.
How about simplify legacy property's getter/setter functions by using some macro instead of calling the above function in itself each time?

2021-02-11 08:09 UTC, kisbg commented
@clover2123  I updated the pull request!

2021-02-15 01:28 UTC, clover2123 commented on src/runtime/GlobalObjectBuiltinRegExp.cpp
> +        ErrorObject::throwBuiltinError(state, ErrorObject::TypeError, "Value is empty");                          \
For error messages, how about exploiting existing messages defined in `ErrorObject::Messages`?
e.g) `ErrorObject::Messages::GlobalObject_ThisNotRegExpObject` for the first error

2021-02-15 01:28 UTC, clover2123 commented on src/runtime/RegExpObject.cpp
> +    state.resolveCallee()->codeBlock()->context()->regexpStatus().rightContext = StringView();
It seems like that `RegExpStatus` could be accessed simply by `state.context()->regexpStatus()`

2021-02-15 07:16 UTC, kisbg commented
@clover2123  Thank you for the review!

2021-02-15 08:54 UTC, clover2123 commented
It seems that you have reverted the previous update.
Please check my comments once more.

2021-02-15 11:36 UTC, kisbg commented
Sorry for the inconvenience!

2021-02-16 02:57 UTC, clover2123 approved these changes
LGTM

2021-02-16 02:59 UTC, ksh8281 approved these changes

2021-02-16 02:59 UTC, merged